name: Download Bing Daily Image

on:
  schedule:
    # 每天 UTC 时间 0 点运行（北京时间 8 点）
    - cron: "0 0 * * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run download script
        run: python download_bing_image.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add daily Bing image"
          git push
